name: Android CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - 'release/*'
    tags:
      - 'v*'

permissions:
  contents: read
  packages: read
  checks: write
  statuses: write

jobs:
  build-and-test:
    name: Build · Unit tests · Lint
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_ACTOR: ${{ github.actor }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Write google-services.json (if secret present)
        if: ${{ github.event_name != 'pull_request' || github.repository == github.event.pull_request.head.repo.full_name }}
        run: |
          if [ -z "$GOOGLE_SERVICES_JSON" ]; then
            echo "GOOGLE_SERVICES_JSON secret is empty — skipping write. Build may fail if file is required."
            exit 0
          fi
          mkdir -p "$GITHUB_WORKSPACE/app"
          printf '%s' "$GOOGLE_SERVICES_JSON" > "$GITHUB_WORKSPACE/app/google-services.json"
          chmod 600 "$GITHUB_WORKSPACE/app/google-services.json"
          echo "Wrote app/google-services.json (size: $(wc -c < $GITHUB_WORKSPACE/app/google-services.json) bytes)"
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
            
            
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties') }}

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build (assembleDebug)
        run: ./gradlew assembleDebug --no-daemon --info --stacktrace

      - name: Run unit tests
        run: ./gradlew test --no-daemon

      - name: Run Android lint
        run: ./gradlew lint --no-daemon

      - name: Upload CI artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-artifacts
          path: |
            app/build/reports
            app/build/outputs
